kind: Namespace
apiVersion: v1

metadata:
  name: prometheus

---

kind: ServiceAccount
apiVersion: v1

metadata:
  name: carol
  namespace: prometheus

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: prometheus-role
  namespace: prometheus

rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: prometheus
  namespace: prometheus

subjects:
  - kind: Group
    name: system:serviceaccount:prometheus

roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: prometheus-role
